apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.operatorName }}
    app.kubernetes.io/name: {{ .Values.operatorName }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: {{ .Values.operatorName }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ .Values.operatorName }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.operatorName }}
  template:
    metadata:
      labels:
        app: {{ .Values.operatorName }}
        {{- if .Values.aadPodIdentity }}
        aadpodidbinding: {{ .Values.aadPodIdentity }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.operatorName }}
      containers:
        - name: {{ .Values.operatorName }}
          image: "{{ .Values.image.keda }}"
          command:
          - keda
          args:
          - '--zap-level={{ .Values.logLevel }}'
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: WATCH_NAMESPACE
              value: {{ .Values.watchNamespace }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: {{ .Values.operatorName }}
          {{- if .Values.grpcTLSCertsSecret }}
          volumeMounts:
          - name: grpc-certs
            mountPath: /grpccerts
          {{- end }}
        {{- if .Values.grpcTLSCertsSecret }}
        volumes:
        - name: grpc-certs
          secret:
            secretName: {{ .Values.grpcTLSCertsSecret }}
        {{- end }}