apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.operatorName }}-metrics-apiserver
    app.kubernetes.io/name: {{ .Values.operatorName }}-metrics-apiserver
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/part-of: {{ .Values.operatorName }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ .Values.operatorName }}-metrics-apiserver
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.operatorName }}-metrics-apiserver
  template:
    metadata:
      labels:
        app: {{ .Values.operatorName }}-metrics-apiserver
        {{- if .Values.aadPodIdentity }}
        aadpodidbinding: {{ .Values.aadPodIdentity }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.operatorName }}
      containers:
        - name: {{ .Values.operatorName }}-metrics-apiserver
          image: {{ .Values.image.metricsAdapter }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: WATCH_NAMESPACE
              value: ""
          args:
          - /usr/local/bin/keda-adapter
          - --secure-port=6443
          - --logtostderr=true
          - --v=0
          ports:
          - containerPort: 6443
            name: https
          - containerPort: 8080
            name: http
          {{- if .Values.grpcTLSCertsSecret }}
          volumeMounts:
          - name: grpc-certs
            mountPath: /grpccerts
          {{- end }}
        {{- if .Values.grpcTLSCertsSecret }}
        volumes:
        - name: grpc-certs
          secret:
            secretName: {{ .Values.grpcTLSCertsSecret }}
        {{- end }}